### ISSUE TITLE
Welcome Back

### ISSUE THREAD

**Issue by ntatoo** [NoxxDev/POGOProtos.NET#1]
Welcome Back Bro @NoxxDev 
we all miss you 
may i ask why did you gone ?
are you going to make a new bot again ?

**Comment by ntatoo** [comment]
@NoxxDev are you there ?

**Comment by NoxxDev** [comment]
@ntatoo Yes, I still don't know if I'm going to redo the bot completely or only the api for third-party projects

**Comment by ntatoo** [comment]
@NoxxDev are you using discord , cuz i like to invite you in it

**Comment by ntatoo** [comment]
@NoxxDev we are create or exacly continue your work 
and we talk in the discord , did you want to join ?

**Comment by ntatoo** [comment]
@NoxxDev the bot that we continue at v.1.0.0.6

**Comment by NoxxDev** [comment]
@ntatoo At the moment, I'm not in discord of NecroBot, if you want to leave an invitation, I will

**Comment by ntatoo** [comment]
You've invited NoxxDev to Necrobot2! They'll be receiving an email shortly. They can also visit https://github.com/Necrobot-Private to accept the invitation.

**Comment by ntatoo** [comment]
@NoxxDev thank you for join us . i hope that we help you a lot at this work .
and if you want to talk in discord . we are hope that

sorry for my bad english

**Comment by ntatoo** [comment]
@NoxxDev may i ask . why did you delete your repo in the first place ?
